//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee_Shop_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProductType
    {
        public TblProductType()
        {
            this.TblProducts = new HashSet<TblProduct>();
        }
    
        public int ProductType { get; set; }
        public string ProductDescription { get; set; }
    
        public virtual ICollection<TblProduct> TblProducts { get; set; }
    }
}
